### ISSUE TITLE
Adding pypi workflow

### ISSUE THREAD

**Issue by MacOS** [noklam/dtype_diet#2]
Hi,

thank you for sharing this package!

Do you mind if I add a workflow that automatically pushes the package to PyPi on release?

Thank you in advance!

Best

**Comment by noklam** [comment]
@MacOS Sorry for picking this up late! Feel free to raise a PR.

**Comment by MacOS** [comment]
@noklam Done!

**Comment by MacOS** [comment]
I'm closing this issue since my PR #3  has been merged.
